export const products = [
  {
    id: 1,
    name: "Dolan Lorem 3 Years Merlot Reserve Red Wine",
    image: "/images/c1.png",
    price: 89.99,
    originalPrice: 120.0,
    rating: 5,
    reviews: 3,
    description: "Premium red wine with rich berry notes and smooth oak finish.",
    discount: "-25%",
    category: "Red Wine",
    bottleSize: "750ml",
    brand: "VESEVO",
  },
  {
    id: 2,
    name: "Moët & Chandon Brut Imperial Champagne",
    image: "/images/c2.png",
    price: 55.0,
    originalPrice: 65.0,
    rating: 5,
    reviews: 12,
    description: "Iconic sparkling champagne with crisp apple and citrus notes.",
    discount: "-15%",
    category: "Champagne",
    bottleSize: "750ml",
    brand: "MOËT",
  },
  {
    id: 3,
    name: "Dark Red Reserve Cabernet Sauvignon",
    image: "/images/c3.png",
    price: 42.0,
    originalPrice: 50.0,
    rating: 4,
    reviews: 8,
    description: "Bold red wine with dark fruit and subtle spice.",
    discount: "-16%",
    category: "Red Wine",
    bottleSize: "750ml",
    brand: "BAREFOOT",
  },
  {
    id: 4,
    name: "Green Label Sparkling Rosé",
    image: "/images/c4.png",
    price: 28.0,
    originalPrice: 28.0,
    rating: 4,
    reviews: 5,
    description: "Light, fruity sparkling rosé with strawberry hints.",
    discount: null,
    category: "Rosé Wine",
    bottleSize: "750ml",
    brand: "VALDO",
  },
  {
    id: 5,
    name: "Jack Daniel's Old No. 7 Tennessee Whiskey",
    image: "/images/c5.png",
    price: 32.0,
    originalPrice: 45.0,
    rating: 5,
    reviews: 30,
    description: "Smooth, charcoal-mellowed Tennessee whiskey.",
    discount: "-29%",
    category: "Spirit Wine",
    bottleSize: "1.5L",
    brand: "JACK DANIEL'S",
  },
  {
    id: 6,
    name: "Perrier-Jouët Grand Brut Champagne",
    image: "/images/c6.png",
    price: 59.99,
    originalPrice: 59.99,
    rating: 5,
    reviews: 7,
    description: "Elegant champagne with floral and pear notes.",
    discount: null,
    category: "Champagne",
    bottleSize: "750ml",
    brand: "PERRIER-JOUËT",
  },
  {
    id: 7,
    name: "Highland Park 12 Year Old Single Malt",
    image: "/images/c7.png",
    price: 65.0,
    originalPrice: 75.0,
    rating: 5,
    reviews: 14,
    description: "Smoky, honeyed Scotch whisky with heather finish.",
    discount: "-13%",
    category: "Spirit Wine",
    bottleSize: "750ml",
    brand: "HIGHLAND PARK",
  },
  {
    id: 8,
    name: "Barefoot Premium Rosé Box",
    image: "/images/c8.png",
    price: 19.99,
    originalPrice: 24.99,
    rating: 4,
    reviews: 22,
    description: "Refreshing boxed rosé – perfect for gatherings.",
    discount: "-20%",
    category: "Rosé Wine",
    bottleSize: "3L",
    brand: "BAREFOOT",
  },
  {
    id: 9,
    name: "Veuve Clicquot Brut Yellow Label",
    image: "/images/c9.png",
    price: 62.0,
    originalPrice: 62.0,
    rating: 5,
    reviews: 18,
    description: "Luxury champagne with brioche and citrus character.",
    discount: null,
    category: "Champagne",
    bottleSize: "750ml",
    brand: "VEUVE CLICQUOT",
  },
  {
    id: 10,
    name: "Château Margaux 2015 Bordeaux",
    image: "/images/c10.png",
    price: 650.0,
    originalPrice: 700.0,
    rating: 5,
    reviews: 3,
    description: "Prestigious red wine with exceptional aging potential.",
    discount: "-7%",
    category: "Red Wine",
    bottleSize: "750ml",
    brand: "CHÂTEAU MARGAUX",
  },
  {
    id: 11,
    name: "Casillero del Diablo Sauvignon Blanc",
    image: "/images/c11.png",
    price: 12.99,
    originalPrice: 12.99,
    rating: 4,
    reviews: 45,
    description: "Crisp white wine with tropical fruit notes.",
    discount: null,
    category: "White Wine",
    bottleSize: "750ml",
    brand: "CONCHA Y TORO",
  },
  {
    id: 12,
    name: "Hennessy VS Cognac",
    image: "/images/c5.png",
    price: 38.0,
    originalPrice: 42.0,
    rating: 5,
    reviews: 27,
    description: "Smooth, versatile cognac with vanilla and oak notes.",
    discount: "-10%",
    category: "Spirit Wine",
    bottleSize: "750ml",
    brand: "HENNESSY",
  },
  {
    id: 13,
    name: "Mumm Napa Brut Prestige",
    image: "/images/c6.png",
    price: 22.0,
    originalPrice: 26.0,
    rating: 4,
    reviews: 9,
    description: "California sparkling wine with apple and toast notes.",
    discount: "-15%",
    category: "Sparkling",
    bottleSize: "750ml",
    brand: "MUMM",
  },
  {
    id: 14,
    name: "Whispering Angel Rosé",
    image: "/images/c7.png",
    price: 24.99,
    originalPrice: 24.99,
    rating: 5,
    reviews: 62,
    description: "World-famous dry rosé from Provence.",
    discount: null,
    category: "Rosé Wine",
    bottleSize: "750ml",
    brand: "CHÂTEAU D'ESCLANS",
  },
  {
    id: 15,
    name: "19 Crimes Red Blend",
    image: "/images/c8.png",
    price: 13.5,
    originalPrice: 15.0,
    rating: 4,
    reviews: 102,
    description: "Bold red with a story - augmented reality labels!",
    discount: "-10%",
    category: "Red Wine",
    bottleSize: "750ml",
    brand: "19 CRIMES",
  },
  {
    id: 16,
    name: "Korbel Sweet Rosé",
    image: "/images/c9.png",
    price: 11.99,
    originalPrice: 11.99,
    rating: 4,
    reviews: 33,
    description: "Affordable sweet sparkling rosé.",
    discount: null,
    category: "Sparkling",
    bottleSize: "750ml",
    brand: "KORBEL",
  },
  {
    id: 17,
    name: "Grey Goose Vodka",
    image: "/images/c10.png",
    price: 35.0,
    originalPrice: 40.0,
    rating: 5,
    reviews: 15,
    description: "Premium French vodka, silky smooth.",
    discount: "-12%",
    category: "Spirit Wine",
    bottleSize: "1.5L",
    brand: "GREY GOOSE",
  },
  {
    id: 18,
    name: "Cloudy Bay Sauvignon Blanc",
    image: "/images/c10.png",
    price: 34.99,
    originalPrice: 34.99,
    rating: 5,
    reviews: 41,
    description: "Iconic New Zealand white wine with zesty acidity.",
    discount: null,
    category: "White Wine",
    bottleSize: "750ml",
    brand: "CLOUDY BAY",
  },
  {
    id: 19,
    name: "Dom Pérignon Vintage 2013",
    image: "/images/c11.png",
    price: 249.99,
    originalPrice: 269.99,
    rating: 5,
    reviews: 6,
    description: "Legendary luxury champagne - complex and refined.",
    discount: "-7%",
    category: "Champagne",
    bottleSize: "750ml",
    brand: "DOM PÉRIGNON",
  },
];